### PR TITLE
Fixed issue 150 and added necessary test file

### LINKED ISSUE #150: Lookup individual bead lots in batch lots
The bead lot entries in the catalog comprise multiple bead collections, and it is assumed that a human looks up the right entries.

For automated use of the tools, however, we will have a single lot number that is only one part of such an entry. As such, we should provide a capability to search for a single lot within the sets.

This should also detect and error on any possible ambiguity that might come from incomplete lot designations (e.g., searching for "AA" rather than "AA01" vs. "AA02"

### PR DESCRIPTION
**Pull request by coverney**
Fix #150 by allowing the user to search for the correct batch without having to type out the entire batch entry from ```BeadCatalog.xlsx```. Also created test file, which ensures that the different functionalities are accounted for.

### CODE REVIEW

**Comment by jakebeal** [comment]
FYI: if you use the "#" format like I edited your comment to do, GitHub will automatically link to the issue.

File: tests/test_get_bead_peaks.m [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+correct_channel = 'FITC';
+incorrect_channel = 'TE';
+no_channel = '';
+
+correct_batch1 = 'Lot AA';
+correct_batch2 = 'AG01';
+incorrect_batch = 'AP02';
+vague_batch = 'Lot AD';
+no_batch = '';
+
```
Comment (jakebeal) [inline tests/test_get_bead_peaks.m]: Can you please also test to confirm backward compatibility if we ask for a complete string, e.g., "Lot AD04, AE01, AF01, AF02, AH01, AH02, AJ01"

File: code/get_bead_peaks.m [hunk 2]
```diff
@@ -13,15 +13,22 @@
...
+    % remove instances of 'Lot' or 'lot' from the input batch
+    batch2 = strrep(batch, 'Lot', '');
+    batch2 = strrep(batch2, 'lot', '');
+    
     % search for a matching model of bead (e.g., 'SpheroTech RCP-30-5A')
     for i=1:numel(catalog)
         modelEntry = catalog{i};
         if strcmp(model,modelEntry{1})
             % search for a matching bead batch, if specified (e.g., 'Lot AG01')
+            num_batch_conflicts = 0;
```
Comment (jakebeal) [inline code/get_bead_peaks.m]: I think this variable would be better named "num_batch_matches"
